### ISSUE TITLE
Sets failing to save correctly when creating

### ISSUE THREAD

**Issue by ffsb07** [hwgilbert16/scholarsome#72] opened 2023-11-24 07:04 UTC
Progress are not saved even save button was clicked when worked for too long.

Progress saved are deleted if you go back and forth from home to your set

Reloading page will delete all the progress >> it seems like it's having problem fetching data after paged refreshed.

>> it's having problem saving the data and retrieving data.

**Comment by hwgilbert16** [comment] 2023-11-24 22:51
> Progress are not saved even save button was clicked when worked for too long.

Could you elaborate on this? Are you saying it will not save if the time spent on the creation/editing page is too long?

> Progress saved are deleted if you go back and forth from home to your set

Does this occur after clicking create/save?

> Reloading page will delete all the progress >> it seems like it's having problem fetching data after paged refreshed.

Are you saying that all progress was lost before clicking create/save? If so, this is expected. Save must be clicked, otherwise the data will not be saved.

**Comment by ffsb07** [comment] 2023-11-25 23:54
The save function is working.
The loading of the page is the issue or the process, IDK what's the technical term.
But after saving the progress and you reload the page,  go back and forth pages, suddenly my progress disappear.
What I did, the first time I encounter this when my progress was halved, I quickly edit the SET and half of the progress retains.
second time I experience it, upon refreshing the retain half was gone, the SET contains 0 items. I decided to delete the SET to make a new one.
For quite some time and many attempts, I realize that after you save your progress, the issue came from the page loading. 
IDK the term, but it's having hard time to fetch the most recent data. So, after reloading the page, I get 0 progress, after a few seconds and refresh the page or back and forth through the pages or even login log out, the progress back to normal.

Sorry for my English,  I think my english is confusing.

**Comment by hwgilbert16** [comment] 2023-11-26 01:28
Alright - to check, the issue occurs when the page is reloaded too quickly after creating a set, e.g. without giving it a few seconds? This is an issue that has been observed before, but unable to be replicated.

No problem about the English. I've got friends too who are learning.

**Comment by ffsb07** [comment] 2023-11-26 02:07
actually it's like 5 seconds at least? it's really not a real quick. 
Even giving it a few more seconds, sometimes it occurs.
I even thought I have problem with my ISP connection. but I don't have problem loading other pages.
I'll try replicating it again today, PST

**Comment by hwgilbert16** [comment] 2023-11-26 02:28
No worries. Let me know whether it is occurring when creating new sets and updating existing ones. i.e. does the issue occur when you update a set that already exists using the save "button," and also when creating new ones using the "create" button?

**Comment by ffsb07** [comment] 2023-11-26 04:01
OKay so I tried again, 
The image below is the result of create button.
Gonna start over again

![image](https://github.com/hwgilbert16/scholarsome/assets/151885689/47c813ad-7472-4de7-818d-da4a0d153478)

**Comment by hwgilbert16** [comment] 2023-11-26 20:36
How many cards did you have present in the set when you tried creating it, did any of them have pictures or text formatting?

**Comment by ffsb07** [comment] 2023-11-27 03:43
at least 10, just a plain text.

**Comment by ffsb07** [comment] 2023-11-27 05:10
I experience it again.
whenever I create, proceed adding cards, worked for too long without saving by clicking the button create,
The /404 page will show up.

So what I did now was create new set,
Named the set
add term and definition on 1 pre created card
Hit the Create button

error page didn't show this time.
I think, since it has not saved yet, it doesn't have a place to hold temporally the data inputted.

Will you change the creation of set?
like if you create a SET, a pop-up window will be prompted , fill-up the Create SET form, then hit save/create SET.
AFter hitting the button, the SET is saved and created before you can add cards.

**Comment by ffsb07** [comment] 2023-11-27 13:16
Progress saving is a real pain.
specially when you made a lot of formatting.
it's so depressing. hahaha
saving and reloading page really lose all data............ 
Hope to see new updates very soon

**Comment by hwgilbert16** [comment] 2023-11-27 13:21
Will definitely be looking into this issue later this week. If you want to try a quick fix, log out and log back in. Expired cookies can sometimes play havoc with authentication when creating sets. 

For right now until this issue is fixed, don't add a bunch of cards all at once when creating sets. Add small amounts at a time after initially creating incase the issue occurs.

**Comment by ffsb07** [comment] 2023-11-27 13:30
I already did that.

Definitely, 1 at a time.

**Comment by hwgilbert16** [comment] 2023-11-28 02:57
I'll take a look into this since this seems to be pretty major.

If you found any patterns of behaviors that may cause the issue, feel free to list them.

**Comment by va3ndf** [comment] 2023-12-21 02:04
I had written out about 50 cards and then pressed save, and it all disappeared. Likely due to me navigating away before the request was done. Very unfortunate.

**Comment by hwgilbert16** [comment] 2023-12-21 02:07
> I had written out about 50 cards and then pressed save, and it all disappeared. Likely due to me navigating away before the request was done. Very unfortunate.

Did you navigate away _while_ the request was still in progress - i.e. it hadn't redirected you to where the new set's page should be? Were you uploading many images while creating the cards?

Been trying to wrestle this issue for weeks.

**Comment by hwgilbert16** [comment] 2023-12-24 20:35
@Green-Robot-Dev-Studios @ffsb07 

A temporary fix for this issue has been applied in the latest release.

**Comment by va3ndf** [comment] 2023-12-25 04:33
Thank you very much! This is shaping up to be a great tool! 🚀

**Comment by OrkunDzgn** [comment] 2023-12-28 21:14
@hwgilbert16 
I know what the issue is. Even though the "Save" button turns into "Edit" right away, the request continues. If you refresh or leave the page before that request returns 200, then you are technically not saving even though the UI makes you think that it is saved.

A spinner and disabled Save button until the save request returns 200 should solve the issue.

The same issue also happens if you haven't been refreshing the page for some time. In that case, what I do is I open another tab to keep my session refreshed, then click save on the flashcard page with that new session that I got from other page. This failed session operation will also be overlooked if you just look at the UI (save button).

Oh by the way, thank you so much for the tool :)

**Comment by hwgilbert16** [comment] 2023-12-29 19:08
> The same issue also happens if you haven't been refreshing the page for some time. In that case, what I do is I open another tab to keep my session refreshed, then click save on the flashcard page with that new session that I got from other page. This failed session operation will also be overlooked if you just look at the UI (save button).

You're right. The issue was that the logic that refreshes the authentication tokens was being superseded by the individual authentication checks for privileged routes. 

---

@Green-Robot-Dev-Studios @ffsb07 @OrkunDzgn 

I pushed a permanent fix for this. If you're using the public version at https://scholarsome.com - the bug is fixed. If you're using a selfhosted local version, then this fix will be in the next update.

**Closed as completed by hwgilbert16** 2023-12-29 19:08 UTC
Labels: bug, high priority
